### PR TITLE
replace vitess atomic helper to uber atomic helper

### PR DESCRIPTION
**Pull request by dk-lockdown**
**What this PR does**:

### CODE REVIEW

**Comment by AlexStocks** [comment]
Pls delete third_party/sync2/atomic.go

**Comment by dk-lockdown** [comment]
> Pls delete third_party/sync2/atomic.go

done!

**Review by AlexStocks — APPROVED** [review]

**Review by AlexStocks — APPROVED** [review]

**Review by Penglq — APPROVED** [review]
LGTM

**Review by Lvnszn — APPROVED** [review]

**Review by sanxun0325 — APPROVED** [review]
LGTM

**Pull request merged**
